### ISSUE TITLE
:no_init gives timeout errors

### ISSUE THREAD

**Issue by Immortalin** [awetzel/exos#3]
Using the :no_init option gives timeout errors that are only fixed if :no_init is replaced with []

**Comment by awetzel** [comment]
if no_init is used, then you cannot use the `require('node_erlastic').server` API which requires the first message to be the parameter of the init function. So if you use no_init, you have to use the more "low level" api which directly handles message send and receive : the Port Duplex `require('node_erlastic').port`.
see https://nodejs.org/api/stream.html#stream_class_stream_duplex for usage , or for example : 

```
var port = require('node_erlastic').port;
port.on('readable', function echo(){
  if(null !== (term = port.read())){
    port.write(term);
    echo();
  }
});
```

see the "server" function implementation as an example of Port duplex usage and to understand how it works : https://github.com/awetzel/node_erlastic/blob/master/main.js#L46-L69

**Comment by Immortalin** [comment]
@awetzel why isn't the `next_term()` call blowing the stack? This is assuming ES6 as the runtime right?
